# X, Y, Z, R, P, Y
# Surge, Sway, Heave, Roll, Pitch, Yaw
T1: [0.7071, -0.7071, 0, 0, 0, 0.1]
T2: [0.7071, 0.7071, 0, 0, 0, -0.1]
T3: [0.7071, -0.7071, 0, 0, 0, 0.1]
T4: [0.7071, 0.7071, 0, 0, 0, -0.1]
T5: [0, 0, -1, 0.5, 0.5, 0]
T6: [0, 0, -1, 0.5, -0.5, 0]
T7: [0, 0, -1, -0.5, -0.5, 0]
T8: [0, 0, -1, -0.5, 0.5, 0]
